version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: developmentDockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: projetovidamendes_production
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 16031973

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 16031973
      MYSQL_DATABASE: projetovidamendes_production
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 16031973
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app      

volumes:
  db_data:
