default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  port: 3306  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: 16031973

development:
  <<: *default
  database: projetovidamendes_production

test:
  <<: *default
  database: projetovidamendes_test

production:
  <<: *default
  database: projetovidamendes_production
